# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input:          GFM
  syntax_highlighter: rouge

# Paginate
plugins:             [jekyll-paginate]
paginate:         1
paginate_path:    "/page/:num"

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jerome Chan
tagline:          "A software designer, talking about codes and design"
description:      "Hello, I&acutem a Java developer at Alibaba. Follow my <a href='https://github.com/jeromechan' target='_blank'>GitHub</a>."
url:              http://aboutcoder.com
baseurl:          /

# Collections
collections:
  slides:
    output:       true

author:
  name:           "Jerome Chan"
  url:            http://weibo.com/5812529126

# Custom vars
version:          2.1.0-u-jeromechan-01

social:
  github:         https://github.com/jeromechan

track:
  cnzz:           1252898702

comment:
  disqus:         aboutcoder
