# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input:          GFM
  syntax_highlighter: rouge

# Paginate
plugins:          [jekyll-paginate]
paginate:         1
paginate_path:    "/page/:num"

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            闲亭居
tagline:          "一个设计者对生活趣事的闲谈"
description:      "闲谈生活趣事，辨识理想现实"
url:              http://jeromedaily.com
baseurl:          /

# Collections
collections:
  slides:
    output:       true

author:
  name:           "Jerome Chan"
  url:            http://weibo.com/5812529126

# Custom vars
version:          2.1.0-u-jeromechan-01

social:
  github:         https://github.com/jeromechan

track:
  cnzz:           1252898702
  baidu:          d8980c7390e74b30a59b00f31e279590

comment:
  disqus:         jeromedaily
